# global configuration
forcefield = "input/tm.v2.offxml"
radius = 4
threads = 4
max_atoms = 80

# parameter-specific config

parameter = [
{id = "t133g", smiles = "output/t133g.smiles", dbscan = {epsilon = 0.5, min_pts = 1}, fragment = false},
{id = "t18b", smiles = "output/t18b.smiles", dbscan = {epsilon = 0.5, min_pts = 1}, fragment = false},
{id = "t87a", smiles = "output/t87a.smiles", dbscan = {epsilon = 0.5, min_pts = 1}, fragment = true},
{id = "t130h", smiles = "output/t130h.smiles", dbscan = {epsilon = 0.5, min_pts = 1}, fragment = true},
{id = "t120h", smiles = "output/t120h.smiles", dbscan = {epsilon = 0.5, min_pts = 1}, fragment = true},
{id = "t119h", smiles = "output/t119h.smiles", dbscan = {epsilon = 0.5, min_pts = 1}, fragment = true},
{id = "t62g", smiles = "output/t62g.smiles", dbscan = {epsilon = 0.5, min_pts = 1}, fragment = true},
{id = "t133h", smiles = "output/t133h.smiles", dbscan = {epsilon = 0.5, min_pts = 1}, fragment = false},
{id = "t61g", smiles = "output/t61g.smiles", dbscan = {epsilon = 0.5, min_pts = 1}, fragment = true},
{id = "t132h", smiles = "output/t132h.smiles", dbscan = {epsilon = 0.5, min_pts = 1}, fragment = true},
{id = "t138a", smiles = "output/t138a.smiles", dbscan = {epsilon = 0.7, min_pts = 1}, fragment = true},
{id = "t118h", smiles = "output/t118h.smiles", dbscan = {epsilon = 0.7, min_pts = 3}, fragment = true},
{id = "t142j", smiles = "output/t142j.smiles", dbscan = {epsilon = 0.7, min_pts = 1}, fragment = true},
{id = "t116i", smiles = "output/t116i.smiles", dbscan = {epsilon = 0.7, min_pts = 1}, fragment = true},
{id = "t89", smiles = "output/t89.smiles", dbscan = {epsilon = 0.7, min_pts = 1}, fragment = true},
{id = "t142k", smiles = "output/t142k.smiles", dbscan = {epsilon = 0.7, min_pts = 5}, fragment = true},
{id = "t101", smiles = "output/t101.smiles", dbscan = {epsilon = 0.7, min_pts = 5}, fragment = true},
{id = "t141", smiles = "output/t141.smiles", dbscan = {epsilon = 0.75, min_pts = 5}, fragment = true},
{id = "t88", smiles = "output/t88.smiles", dbscan = {epsilon = 0.7, min_pts = 5}, fragment = true},
{id = "t18a", smiles = "output/t18a.smiles", dbscan = {epsilon = 0.7, min_pts = 5}, fragment = true},
{id = "t116j", smiles = "output/t116j.smiles", dbscan = {epsilon = 0.75, min_pts = 10}, fragment = true},
{id = "t72h", smiles = "output/t72h.smiles", dbscan = {epsilon = 0.7, min_pts = 10}, fragment = true},
{id = "t115h", smiles = "output/t115h.smiles", dbscan = {epsilon = 0.75, min_pts = 5}, fragment = true},
{id = "t165", smiles = "output/t165.smiles", dbscan = {epsilon = 0.75, min_pts = 5}, fragment = true},
{id = "t141b", smiles = "output/t141b.smiles", dbscan = {epsilon = 0.75, min_pts = 10}, fragment = true},
{id = "t83h", smiles = "output/t83h.smiles", dbscan = {epsilon = 0.7, min_pts = 10}, fragment = true},
# {id = "t141c", smiles = "output/t141c.smiles", dbscan = {epsilon = 0.5, min_pts = 1}, fragment = true},
]
